services:
  node:
    build:
      dockerfile: ./DockerFile.devcontainer
    container_name: three-js
    stdin_open: true
    tty: true
    ports:
     - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    volumes:
      - ./:/workspace/jinx


